/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

/**
 *
 * @author gerviz
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        //atualiza os sliders comforme as definições
        comeco.addChangeListener(e -> {
            changePassoMax();
            passo.setMinimum(1);
            int valor = comeco.getValue();
            numIni.setText(String.valueOf(valor));
            if(fim.getValue() <= valor){
                fim.setValue(valor+1);
            }
        });

        fim.addChangeListener(e -> {
            changePassoMax();
            passo.setMinimum(1);
            int valor = fim.getValue();
            numFim.setText(String.valueOf(valor));
            if (comeco.getValue() >= valor){
            comeco.setValue(valor - 1);
            }
        });

        passo.addChangeListener(e -> {
            int valor = passo.getValue();
            numPass.setText(String.valueOf(valor));
            if(passo.getValue() == 0){
            passo.setValue(1);
            }
        });
    }
    //muda o maximo do passo
    private void changePassoMax() {
    int passoMax = fim.getValue() - comeco.getValue();

    passo.setMaximum(passoMax);

    if (passo.getValue() > passoMax) {
        passo.setValue(passoMax);
    }

    numPass.setText(String.valueOf(passo.getValue()));
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comeco = new javax.swing.JSlider();
        fim = new javax.swing.JSlider();
        passo = new javax.swing.JSlider();
        contar = new javax.swing.JButton();
        numIni = new javax.swing.JLabel();
        numFim = new javax.swing.JLabel();
        numPass = new javax.swing.JLabel();
        numIni1 = new javax.swing.JLabel();
        numFim1 = new javax.swing.JLabel();
        numPass1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nums = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comeco.setMaximum(10);
        comeco.setValue(0);
        comeco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comeco.setDoubleBuffered(true);
        getContentPane().add(comeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 14, -1, -1));

        fim.setMinimum(1);
        fim.setValue(10);
        getContentPane().add(fim, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 40, -1, -1));

        passo.setMinimum(1);
        passo.setValue(2);
        getContentPane().add(passo, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 66, -1, -1));

        contar.setText("contar");
        getContentPane().add(contar, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 104, -1, -1));
        // conta e adiciona no textArea
        contar.addActionListener(e -> {
            int inicio = comeco.getValue();
            int fimValor = fim.getValue();
            int passoValor = passo.getValue();

            StringBuilder contagem = new StringBuilder();

            for (int i = inicio; i <= fimValor; i += passoValor) {
                contagem.append(i).append("\n");
            }

            nums.setText(contagem.toString());
        });

        numIni.setText("0");
        getContentPane().add(numIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 14, 17, -1));

        numFim.setText("10");
        getContentPane().add(numFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 40, -1, -1));

        numPass.setText("2");
        getContentPane().add(numPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 68, -1, -1));

        numIni1.setText("Inicio:");
        getContentPane().add(numIni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 18, -1, -1));

        numFim1.setText("Fim:");
        getContentPane().add(numFim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 42, -1, -1));

        numPass1.setText("Passo:");
        getContentPane().add(numPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 68, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        nums.setEditable(false);
        nums.setColumns(20);
        nums.setRows(5);
        jScrollPane1.setViewportView(nums);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 180, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider comeco;
    private javax.swing.JButton contar;
    private javax.swing.JSlider fim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numFim;
    private javax.swing.JLabel numFim1;
    private javax.swing.JLabel numIni;
    private javax.swing.JLabel numIni1;
    private javax.swing.JLabel numPass;
    private javax.swing.JLabel numPass1;
    private javax.swing.JTextArea nums;
    private javax.swing.JSlider passo;
    // End of variables declaration//GEN-END:variables
}
