/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade17.view;

import br.com.ifba.atividade17.curso.controller.CursoController;
import br.com.ifba.atividade17.curso.entity.CursoA17;
import br.com.ifba.atividade17.tableModel.TableCursoModel;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author gerviz
 */
@Component
public class AddOrEditCurso extends javax.swing.JDialog {

  @Autowired
  private CursoController controller;

  boolean editando = false;
  CursoA17 cursoOriginal = new CursoA17();
  public TableCursoModel table;

  /**
   * Creates new form AddCurso
   */
  public AddOrEditCurso() {
    super();
    initComponents();
  }

  public AddOrEditCurso(java.awt.Frame parent, boolean modal, boolean edit, CursoA17 curso) {
    super(parent, modal);
    initComponents();
    //define se a tela estara no modo de edicao ou nao
    if (edit) {
      txtInName.setText(curso.getNome());
      txtInCod.setText(curso.getCodigoCurso());
      chkInActive.setSelected(curso.isAtivo());
      btnAdd.setText("Editar");
      lblId.setText("id: " + curso.getId());
      editando = true;
      cursoOriginal = curso;
    }
  }

  public AddOrEditCurso(java.awt.Frame parent, boolean modal, boolean edit, CursoA17 curso, TableCursoModel table) {
    super(parent, modal);
    this.table = table;
    initComponents();
    if (edit && curso != null) {
      txtInName.setText(curso.getNome());
      txtInCod.setText(curso.getCodigoCurso());
      chkInActive.setSelected(curso.isAtivo());
      btnAdd.setText("Editar");
      lblId.setText("id: " + curso.getId());
      editando = true;
      cursoOriginal = curso;
    } else {
      editando = false;
      cursoOriginal = new CursoA17();
    }
  }

  public AddOrEditCurso(CursoListar parent, boolean modal, boolean edit, CursoA17 curso, TableCursoModel table, CursoController controller) {
    super(parent, modal);
    this.table = table;
    this.controller = controller;
    initComponents();
    if (edit && curso != null) {
      txtInName.setText(curso.getNome());
      txtInCod.setText(curso.getCodigoCurso());
      chkInActive.setSelected(curso.isAtivo());
      btnAdd.setText("Editar");
      lblId.setText("id: " + curso.getId());
      editando = true;
      cursoOriginal = curso;
    } else {
      editando = false;
      cursoOriginal = new CursoA17();
    }
  }

  public void limparCampos() {
    txtInCod.setText("");
    txtInName.setText("");
    lblId.setText("");
    chkInActive.setSelected(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblTxtName = new javax.swing.JLabel();
    lblTxtCod = new javax.swing.JLabel();
    lblTxtActive = new javax.swing.JLabel();
    chkInActive = new javax.swing.JCheckBox();
    txtInCod = new javax.swing.JTextField();
    txtInName = new javax.swing.JTextField();
    btnCancel = new javax.swing.JButton();
    btnAdd = new javax.swing.JButton();
    lblId = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Preencha os dados do curso");
    setAutoRequestFocus(false);
    setIconImages(null);
    setName("AddCurso"); // NOI18N
    setResizable(false);
    setSize(new java.awt.Dimension(390, 250));
    setType(java.awt.Window.Type.UTILITY);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblTxtName.setText("nome:");
    getContentPane().add(lblTxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 25, -1, -1));

    lblTxtCod.setText("codigo:");
    getContentPane().add(lblTxtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 85, -1, -1));

    lblTxtActive.setText("Ativo:");
    getContentPane().add(lblTxtActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 141, -1, -1));
    getContentPane().add(chkInActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 141, -1, -1));
    getContentPane().add(txtInCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 82, 100, -1));
    getContentPane().add(txtInName, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 22, 300, -1));

    btnCancel.setText("Cancelar");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });
    getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

    btnAdd.setText("Adicionar");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });
    getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));
    getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    txtInCod.setText("");
    txtInName.setText("");
    chkInActive.setSelected(false);
    lblId.setText("");
    this.dispose();
  }//GEN-LAST:event_btnCancelActionPerformed

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    if (txtInName.getText().isBlank() || txtInCod.getText().isBlank()) {
      JOptionPane.showMessageDialog(
          null,
          "Preencha todos os campos! H[31;1mHá algo em branco.",
          "Erro",
          JOptionPane.ERROR_MESSAGE
      );
    } else {
      CursoA17 curso = new CursoA17();
      curso.setNome(txtInName.getText());
      curso.setCodigoCurso(txtInCod.getText());
      curso.setAtivo(chkInActive.isSelected());
      if (editando) {
        curso.setId(cursoOriginal.getId());
        controller.update(curso);
        limparCampos();
        JOptionPane.showMessageDialog(this, "Curso editado com sucesso!");
      } else {
        controller.save(curso);
        limparCampos();
        JOptionPane.showMessageDialog(this, "Curso adicionado com sucesso!");
      }
      if (table != null) {
        table.setDados(controller.findAll());
        table.fireTableDataChanged();
      }
      this.dispose();
    }
  }//GEN-LAST:event_btnAddActionPerformed

  /**
   * @param args the command line arguments
   */
  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnCancel;
  private javax.swing.JCheckBox chkInActive;
  private javax.swing.JLabel lblId;
  private javax.swing.JLabel lblTxtActive;
  private javax.swing.JLabel lblTxtCod;
  private javax.swing.JLabel lblTxtName;
  private javax.swing.JTextField txtInCod;
  private javax.swing.JTextField txtInName;
  // End of variables declaration//GEN-END:variables
}
