/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade12.view;

import br.com.ifba.atividade12.entity.Curso;
import br.com.ifba.atividade12.util.CursoSave;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author gerviz
 */
public class AddOrEditCurso extends javax.swing.JDialog {

  CursoSave manager = new CursoSave();
  boolean editando = false;
  Curso cursoOriginal = new Curso();

  /**
   * Creates new form AddCurso
   */
  public AddOrEditCurso(java.awt.Frame parent, boolean modal, boolean edit, Curso curso) {
    super(parent, modal);
    initComponents();

    if (edit) {
      txtInName.setText(curso.getNome());
      txtInCod.setText(curso.getCodigoCurso());
      chkInActive.setSelected(curso.isAtivo());
      btnAdd.setText("Editar");
      lblId.setText("" + curso.getId());
      editando = true;
      cursoOriginal = curso;
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblTxtName = new javax.swing.JLabel();
    lblTxtCod = new javax.swing.JLabel();
    lblTxtActive = new javax.swing.JLabel();
    chkInActive = new javax.swing.JCheckBox();
    txtInCod = new javax.swing.JTextField();
    txtInName = new javax.swing.JTextField();
    btnCancel = new javax.swing.JButton();
    btnAdd = new javax.swing.JButton();
    lblId = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Preencha os dados do curso");
    setAutoRequestFocus(false);
    setIconImages(null);
    setName("AddCurso"); // NOI18N
    setPreferredSize(new java.awt.Dimension(390, 250));
    setResizable(false);
    setSize(new java.awt.Dimension(390, 250));
    setType(java.awt.Window.Type.UTILITY);
    addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        formFocusLost(evt);
      }
    });
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblTxtName.setText("nome:");
    getContentPane().add(lblTxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 25, -1, -1));

    lblTxtCod.setText("codigo:");
    getContentPane().add(lblTxtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 85, -1, -1));

    lblTxtActive.setText("Ativo:");
    getContentPane().add(lblTxtActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 141, -1, -1));

    chkInActive.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        chkInActiveActionPerformed(evt);
      }
    });
    getContentPane().add(chkInActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 141, -1, -1));
    getContentPane().add(txtInCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 82, 100, -1));

    txtInName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInNameActionPerformed(evt);
      }
    });
    getContentPane().add(txtInName, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 22, 300, -1));

    btnCancel.setText("Cancelar");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });
    getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

    btnAdd.setText("Adicionar");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });
    getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));
    getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void chkInActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkInActiveActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_chkInActiveActionPerformed

  private void txtInNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInNameActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtInNameActionPerformed

  private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
  }//GEN-LAST:event_formFocusLost

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    this.dispose();
  }//GEN-LAST:event_btnCancelActionPerformed

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    if (txtInName.getText().isBlank() || txtInCod.getText().isBlank()) {
      JOptionPane.showMessageDialog(
          null,
          "Preencha todos os campos! Há algo em branco.",
          "Erro",
          JOptionPane.ERROR_MESSAGE
      );
    } else {
      if (editando) {
        Curso curso = null;
        curso.setNome(txtInName.getText());
        curso.setCodigoCurso(txtInCod.getText());
        curso.setAtivo(chkInActive.isSelected());
        curso.setId(cursoOriginal.getId());
        manager.saveCurso(curso);
      } else {
        Curso curso = null;
        curso.setNome(txtInName.getText());
        curso.setCodigoCurso(txtInCod.getText());
        curso.setAtivo(chkInActive.isSelected());
        manager.saveCurso(curso);
      }
    }
  }//GEN-LAST:event_btnAddActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(AddOrEditCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(AddOrEditCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(AddOrEditCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AddOrEditCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    //</editor-fold>

    /* Create and display the form */
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnCancel;
  private javax.swing.JCheckBox chkInActive;
  private javax.swing.JLabel lblId;
  private javax.swing.JLabel lblTxtActive;
  private javax.swing.JLabel lblTxtCod;
  private javax.swing.JLabel lblTxtName;
  private javax.swing.JTextField txtInCod;
  private javax.swing.JTextField txtInName;
  // End of variables declaration//GEN-END:variables
}
