/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;

import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author gerviz
 */
public class MainFrame extends javax.swing.JFrame {

     private ImageIcon originalPessoa;
     private ImageIcon originalCalc;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        Calcular.addActionListener(e -> calcularIdade());

         // Carrega a imagem original
        originalPessoa = new ImageIcon(getClass().getResource("/br/com/ifba/atividade03/images/pessoa.jpeg"));
        originalCalc = new ImageIcon(getClass().getResource("/br/com/ifba/atividade03/images/calculadora.png"));
        // Redimensiona ao iniciar
        ajustarImagens();

        // Atualiza a imagem sempre que o label for redimensionado
        imgPessoa.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                ajustarImagens();
            }
        });
        
        Calcular.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                ajustarImagens();
            }
        });
    }

    private void calcularIdade() {
    int anoNascimento = (int) yearSelector.getValue();
    int anoAtual = java.time.Year.now().getValue();
    int idade = anoAtual - anoNascimento;

    IdadeCalculada.setText(String.valueOf(idade));
}

    //ajusta imagens
    private void ajustarImagens() {
    if (originalPessoa != null && imgPessoa.getWidth() > 0 && imgPessoa.getHeight() > 0) {
        Image imagemRedimensionada = originalPessoa.getImage().getScaledInstance(
                imgPessoa.getWidth(), imgPessoa.getHeight(), Image.SCALE_SMOOTH);
        imgPessoa.setIcon(new ImageIcon(imagemRedimensionada));
    }
    if (originalCalc != null && Calcular.getWidth() > 0 && Calcular.getHeight() > 0) {
        Image imagemRedimensionada = originalCalc.getImage().getScaledInstance(
                40,40 , Image.SCALE_SMOOTH);
        Calcular.setIcon(new ImageIcon(imagemRedimensionada));
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAnoNasc = new javax.swing.JLabel();
        yearSelector = new javax.swing.JSpinner();
        Calcular = new javax.swing.JButton();
        Idade = new javax.swing.JLabel();
        IdadeCalculada = new javax.swing.JLabel();
        imgPessoa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de idade");
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setSize(new java.awt.Dimension(15, 0));

        txtAnoNasc.setText("ano de nascimento:");
        txtAnoNasc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        yearSelector.setValue(2025);

        Calcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/images/calculadora.png"))); // NOI18N
        Calcular.setText("Calcular");
        Calcular.setPreferredSize(new java.awt.Dimension(213, 231));

        Idade.setText("Idade:");

        IdadeCalculada.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        IdadeCalculada.setForeground(new java.awt.Color(255, 0, 0));
        IdadeCalculada.setText("0");

        imgPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/images/pessoa.jpeg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Idade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdadeCalculada))
                    .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAnoNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnoNasc)
                            .addComponent(yearSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Idade)
                            .addComponent(IdadeCalculada))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel Idade;
    private javax.swing.JLabel IdadeCalculada;
    private javax.swing.JLabel imgPessoa;
    private javax.swing.JLabel txtAnoNasc;
    private javax.swing.JSpinner yearSelector;
    // End of variables declaration//GEN-END:variables
}
