/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

/**
 *
 * @author gerviz
 */
public class MainFrame extends javax.swing.JFrame {

  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    initComponents();

    //atualiza os sliders comforme as definições
    sldComeco.addChangeListener(e -> {
      changePassoMax();
      sldPasso.setMinimum(1);
      int valor = sldComeco.getValue();
      lblNumIni.setText(String.valueOf(valor));
      if (sldFim.getValue() <= valor) {
        sldFim.setValue(valor + 1);
      }
    });

    sldFim.addChangeListener(e -> {
      changePassoMax();
      sldPasso.setMinimum(1);
      int valor = sldFim.getValue();
      lblNumFim.setText(String.valueOf(valor));
      if (sldComeco.getValue() >= valor) {
        sldComeco.setValue(valor - 1);
      }
    });

    sldPasso.addChangeListener(e -> {
      int valor = sldPasso.getValue();
      lblNumPass.setText(String.valueOf(valor));
      if (sldPasso.getValue() == 0) {
        sldPasso.setValue(1);
      }
    });
  }
  //muda o maximo do passo

  private void changePassoMax() {
    int passoMax = sldFim.getValue() - sldComeco.getValue();

    sldPasso.setMaximum(passoMax);

    if (sldPasso.getValue() > passoMax) {
      sldPasso.setValue(passoMax);
    }

    lblNumPass.setText(String.valueOf(sldPasso.getValue()));
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sldComeco = new javax.swing.JSlider();
        sldFim = new javax.swing.JSlider();
        sldPasso = new javax.swing.JSlider();
        btnContar = new javax.swing.JButton();
        lblNumIni = new javax.swing.JLabel();
        lblNumFim = new javax.swing.JLabel();
        lblNumPass = new javax.swing.JLabel();
        lblIniTxt = new javax.swing.JLabel();
        lblFimTxt = new javax.swing.JLabel();
        lblPassTxt = new javax.swing.JLabel();
        scrlNumFinalTxt = new javax.swing.JScrollPane();
        nums = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sldComeco.setMaximum(10);
        sldComeco.setValue(0);
        sldComeco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldComeco.setDoubleBuffered(true);

        sldFim.setMinimum(1);
        sldFim.setValue(10);

        sldPasso.setMinimum(1);
        sldPasso.setValue(2);

        btnContar.setText("contar");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });

        lblNumIni.setText("0");

        lblNumFim.setText("10");

        lblNumPass.setText("2");

        lblIniTxt.setText("Inicio:");

        lblFimTxt.setText("Fim:");

        lblPassTxt.setText("Passo:");

        scrlNumFinalTxt.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        nums.setEditable(false);
        nums.setColumns(20);
        nums.setRows(5);
        scrlNumFinalTxt.setViewportView(nums);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIniTxt)
                    .addComponent(lblFimTxt)
                    .addComponent(lblPassTxt))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldComeco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnContar)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumIni, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumFim)
                    .addComponent(lblNumPass))
                .addGap(15, 15, 15)
                .addComponent(scrlNumFinalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblIniTxt)
                .addGap(6, 6, 6)
                .addComponent(lblFimTxt)
                .addGap(8, 8, 8)
                .addComponent(lblPassTxt))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(sldComeco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(sldFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(sldPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContar))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNumIni)
                .addGap(8, 8, 8)
                .addComponent(lblNumFim)
                .addGap(10, 10, 10)
                .addComponent(lblNumPass))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(scrlNumFinalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        // conta e adiciona no textArea
        btnContar.addActionListener(e -> {
            int inicio = sldComeco.getValue();
            int fimValor = sldFim.getValue();
            int passoValor = sldPasso.getValue();

            StringBuilder contagem = new StringBuilder();

            for (int i = inicio; i <= fimValor; i += passoValor) {
                contagem.append(i).append("\n");
            }

            nums.setText(contagem.toString());
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_btnContarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainFrame().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContar;
    private javax.swing.JLabel lblFimTxt;
    private javax.swing.JLabel lblIniTxt;
    private javax.swing.JLabel lblNumFim;
    private javax.swing.JLabel lblNumIni;
    private javax.swing.JLabel lblNumPass;
    private javax.swing.JLabel lblPassTxt;
    private javax.swing.JTextArea nums;
    private javax.swing.JScrollPane scrlNumFinalTxt;
    private javax.swing.JSlider sldComeco;
    private javax.swing.JSlider sldFim;
    private javax.swing.JSlider sldPasso;
    // End of variables declaration//GEN-END:variables
}
