/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade11.view;

import br.com.ifba.atividade11.forma.FormList;
import br.com.ifba.atividade11.forma.Forma;
import br.com.ifba.atividade11.forma.bidimensional.formas.Circulo;
import br.com.ifba.atividade11.forma.bidimensional.formas.Quadrado;
import br.com.ifba.atividade11.forma.bidimensional.formas.Triangulo;
import br.com.ifba.atividade11.forma.tridimensional.formas.Cubo;
import br.com.ifba.atividade11.forma.tridimensional.formas.Esfera;
import br.com.ifba.atividade11.forma.tridimensional.formas.Piramide;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.math.NumberUtils;

/**
 *
 * @author gerviz
 */
public class CreationFrame extends javax.swing.JFrame {

  private MainFrame mainFrame;
  private FormList formList;

  /**
   * Creates new form CreationFrame
   */
  public CreationFrame(MainFrame mainFrame, FormList formList) {
    this.mainFrame = mainFrame;
    this.formList = formList;
    initComponents();
    esconderComponentes();
  }
// checa se algo e um numero

  public boolean isNumber(String algo) {
    boolean isNumber = NumberUtils.isCreatable(algo);
    return isNumber;
  }
//verifica se campos foram preenchidos antes de liberar alguns itens

  private void verificarCampos() {
    boolean ok = true;
    if (txtInputParameter1.isVisible()) {
      ok &= !txtInputParameter1.getText().trim().isEmpty() && isNumber(txtInputParameter1.getText());
    }
    if (txtInputParameter2.isVisible()) {
      ok &= !txtInputParameter2.getText().trim().isEmpty() && isNumber(txtInputParameter2.getText());
    }
    if (txtInputParameter3.isVisible()) {
      ok &= !txtInputParameter3.getText().trim().isEmpty() && isNumber(txtInputParameter3.getText());
    }
    lblTxtName.setVisible(ok);
    txtInputName.setVisible(ok);
    if (ok) {
      if (txtInputName.isVisible()) {
        if (!txtInputName.getText().trim().isEmpty()) {
          btnAdd.setVisible(true);
        }
      }
    } else {
      btnAdd.setVisible(false);
    }
  }
// verifica se algum campo é zero

  private boolean verificarCamposZero() {
    boolean temZero = false;
    if (txtInputParameter1.isVisible()) {
      try {
        temZero |= Double.parseDouble(txtInputParameter1.getText().trim()) == 0.0;
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Algo diferente de números "
            + "digitado em algum dos parâmetros.");

      }
    }
    if (txtInputParameter2.isVisible()) {
      try {
        temZero |= Double.parseDouble(txtInputParameter2.getText().trim()) == 0.0;
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Algo diferente de números "
            + "digitado em algum dos parâmetros.");
      }

    }
    if (txtInputParameter3.isVisible()) {
      try {
        temZero |= Double.parseDouble(txtInputParameter3.getText().trim()) == 0.0;
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Algo diferente de números "
            + "digitado em algum dos parâmetros.");
      }
    }
    return temZero;
  }
// esconde quase todos os componentes

  private void esconderComponentes() {
    btn3Sides.setVisible(false);
    btnBAndH.setVisible(false);
    btnAdd.setVisible(false);
    cbFormSelector.setVisible(false);
    lblTxtName.setVisible(false);
    lblTxtParameter1.setVisible(false);
    lblTxtParameter2.setVisible(false);
    lblTxtParameter3.setVisible(false);
    lblTxtSelectForm.setVisible(false);
    txtInputParameter1.setVisible(false);
    txtInputParameter2.setVisible(false);
    txtInputParameter3.setVisible(false);
    txtInputName.setVisible(false);
  }
// esconde alguns componentes referentes aos parametros

  private void esconderParametros() {
    btn3Sides.setVisible(false);
    btnBAndH.setVisible(false);
    btnAdd.setVisible(false);
    lblTxtParameter1.setVisible(false);
    lblTxtParameter2.setVisible(false);
    lblTxtParameter3.setVisible(false);
    txtInputParameter1.setVisible(false);
    txtInputParameter2.setVisible(false);
    txtInputParameter3.setVisible(false);
    btnGpDataType.clearSelection();
    txtInputParameter1.setText("");
    txtInputParameter2.setText("");
    txtInputParameter3.setText("");
    lblTxtName.setVisible(false);
    txtInputName.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnGpBiOrTri = new javax.swing.ButtonGroup();
    btnGpDataType = new javax.swing.ButtonGroup();
    btnBi = new javax.swing.JRadioButton();
    btnTri = new javax.swing.JRadioButton();
    cbFormSelector = new javax.swing.JComboBox<>();
    btnBAndH = new javax.swing.JRadioButton();
    btn3Sides = new javax.swing.JRadioButton();
    txtInputParameter1 = new javax.swing.JTextField();
    txtInputParameter2 = new javax.swing.JTextField();
    txtInputParameter3 = new javax.swing.JTextField();
    lblTxtSelectForm = new javax.swing.JLabel();
    lblTxtParameter1 = new javax.swing.JLabel();
    lblTxtParameter2 = new javax.swing.JLabel();
    lblTxtParameter3 = new javax.swing.JLabel();
    btnAdd = new javax.swing.JToggleButton();
    txtInputName = new javax.swing.JTextField();
    lblTxtName = new javax.swing.JLabel();

    setTitle("Formas Geométricas");
    setAutoRequestFocus(false);
    setPreferredSize(new java.awt.Dimension(400, 201));
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnGpBiOrTri.add(btnBi);
    btnBi.setText("Bidimensional");
    btnBi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBiActionPerformed(evt);
      }
    });
    getContentPane().add(btnBi, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 7, -1, -1));

    btnGpBiOrTri.add(btnTri);
    btnTri.setText("Tridimensional");
    btnTri.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTriActionPerformed(evt);
      }
    });
    getContentPane().add(btnTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 7, -1, -1));

    cbFormSelector.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbFormSelectorActionPerformed(evt);
      }
    });
    getContentPane().add(cbFormSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 49, 80, -1));

    btnGpDataType.add(btnBAndH);
    btnBAndH.setText("base/altura");
    btnBAndH.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBAndHActionPerformed(evt);
      }
    });
    getContentPane().add(btnBAndH, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 7, -1, -1));

    btnGpDataType.add(btn3Sides);
    btn3Sides.setText("3 lados");
    btn3Sides.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn3SidesActionPerformed(evt);
      }
    });
    getContentPane().add(btn3Sides, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 7, -1, -1));

    txtInputParameter1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInputParameter1ActionPerformed(evt);
      }
    });
    getContentPane().add(txtInputParameter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 86, 70, -1));

    txtInputParameter2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInputParameter2ActionPerformed(evt);
      }
    });
    getContentPane().add(txtInputParameter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 118, 70, -1));

    txtInputParameter3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInputParameter3ActionPerformed(evt);
      }
    });
    getContentPane().add(txtInputParameter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 150, 70, -1));

    lblTxtSelectForm.setText("selecione a forma:");
    getContentPane().add(lblTxtSelectForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

    lblTxtParameter1.setText("jLabel2");
    getContentPane().add(lblTxtParameter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 88, -1, -1));

    lblTxtParameter2.setText("jLabel3");
    getContentPane().add(lblTxtParameter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

    lblTxtParameter3.setText("jLabel4");
    getContentPane().add(lblTxtParameter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 152, -1, -1));

    btnAdd.setText("Adicionar");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });
    getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

    txtInputName.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInputNameActionPerformed(evt);
      }
    });
    getContentPane().add(txtInputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 60, -1));

    lblTxtName.setText("nome:");
    getContentPane().add(lblTxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBiActionPerformed
    //retira todos os itens do combobox para adicionar somente os bi ou tridimensionais
    cbFormSelector.removeAllItems();
    cbFormSelector.addItem("circulo");
    cbFormSelector.addItem("triangulo");
    cbFormSelector.addItem("quadrado");
    cbFormSelector.addItem("");
    cbFormSelector.setSelectedIndex(3);
    cbFormSelector.setVisible(true);
    lblTxtSelectForm.setVisible(true);
  }//GEN-LAST:event_btnBiActionPerformed

  private void btnTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriActionPerformed
    //retira todos os itens do combobox para adicionar somente os bi ou tridimensionais
    cbFormSelector.removeAllItems();
    cbFormSelector.addItem("cubo");
    cbFormSelector.addItem("piramide");
    cbFormSelector.addItem("esfera");
    cbFormSelector.addItem("");
    cbFormSelector.setSelectedIndex(3);
    cbFormSelector.setVisible(true);
    lblTxtSelectForm.setVisible(true);
  }//GEN-LAST:event_btnTriActionPerformed

  private void cbFormSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormSelectorActionPerformed
// pega a forma selecionada no combobox e deixa campos suficientes visiveis
    int formaIndex = (int) cbFormSelector.getSelectedIndex();
    if (btnBi.isSelected()) {
      switch (formaIndex) {
        case 0 -> {
          esconderParametros();
          lblTxtParameter1.setText("Raio:");
          lblTxtParameter1.setVisible(true);
          txtInputParameter1.setVisible(true);
        }
        case 1 -> {
          esconderParametros();
          btn3Sides.setVisible(true);
          btnBAndH.setVisible(true);
        }
        case 2 -> {
          esconderParametros();
          lblTxtParameter1.setText("Lado:");
          lblTxtParameter1.setVisible(true);
          txtInputParameter1.setVisible(true);
        }
        default -> {
          esconderParametros();
        }
      }
    } else {
      switch (formaIndex) {
        case 0:
          esconderParametros();
          lblTxtParameter1.setText("Lado:");
          lblTxtParameter1.setVisible(true);
          txtInputParameter1.setVisible(true);
          break;
        case 1:
          esconderParametros();
          lblTxtParameter1.setText("Lado:");
          lblTxtParameter1.setVisible(true);
          txtInputParameter1.setVisible(true);
          lblTxtParameter2.setText("Altura:");
          lblTxtParameter2.setVisible(true);
          txtInputParameter2.setVisible(true);
          break;
        case 2:
          esconderParametros();
          lblTxtParameter1.setText("Raio:");
          lblTxtParameter1.setVisible(true);
          txtInputParameter1.setVisible(true);
          break;
        default:
          lblTxtParameter1.setVisible(false);
          lblTxtParameter2.setVisible(false);
          lblTxtParameter3.setVisible(false);
          txtInputParameter1.setVisible(false);
          txtInputParameter2.setVisible(false);
          txtInputParameter3.setVisible(false);
      }
    }
  }//GEN-LAST:event_cbFormSelectorActionPerformed

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    //checa se é
    String formaSelecionada = (String) cbFormSelector.getSelectedItem();
    Forma forma = null;
    if (verificarCamposZero()) {
      JOptionPane.showMessageDialog(this, "Preencha os parâmetros corretamente.");
    } else {
      try {
        if (btnBi.isSelected()) {
          switch (formaSelecionada) {
            case "circulo" -> {
              double raio = Double.parseDouble(txtInputParameter1.getText());
              forma = new Circulo(raio);

            }
            case "triangulo" -> {
              if (btn3Sides.isSelected()) {
                double lado1 = Double.parseDouble(txtInputParameter1.getText());
                double lado2 = Double.parseDouble(txtInputParameter2.getText());
                double lado3 = Double.parseDouble(txtInputParameter3.getText());
                if (lado1 + lado2 > lado3 && lado2 + lado3 > lado1 && lado1 + lado3 > lado2) {
                  forma = new Triangulo(lado1, lado2, lado3);
                } else {
                  JOptionPane.showMessageDialog(null, "Lados inválidos para formar um triângulo.");
                  forma = null;
                }
              } else if (btnBAndH.isSelected()) {
                double base = Double.parseDouble(txtInputParameter1.getText());
                double altura = Double.parseDouble(txtInputParameter2.getText());
                forma = new Triangulo(base, altura);
              }
            }

            case "quadrado" -> {
              double lado = Double.parseDouble(txtInputParameter1.getText());
              forma = new Quadrado(lado);
            }
          }
        } else if (btnTri.isSelected()) {
          switch (formaSelecionada) {
            case "cubo" -> {
              double lado = Double.parseDouble(txtInputParameter1.getText());
              forma = new Cubo(lado);
            }
            case "piramide" -> {
              double lado = Double.parseDouble(txtInputParameter1.getText());
              double altura = Double.parseDouble(txtInputParameter2.getText());
              forma = new Piramide(lado, altura);
            }
            case "esfera" -> {
              double raio = Double.parseDouble(txtInputParameter1.getText());
              forma = new Esfera(raio);
            }
          }
        }

        if (forma != null) {
          forma.setNome(txtInputName.getText());
          formList.adicionarForma(forma);
          JOptionPane.showMessageDialog(this, "Forma adicionada com sucesso.");
          mainFrame.atualizarBx();
          dispose();
        } else {
          JOptionPane.showMessageDialog(this, "Selecione uma forma válida.");
        }
      } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Preencha os parâmetros corretamente.");
      }
    }

  }//GEN-LAST:event_btnAddActionPerformed

  private void btnBAndHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBAndHActionPerformed
    //esconde/mostra componentes referentes ao tipo do botao(base/altura)
    lblTxtName.setVisible(false);
    txtInputName.setVisible(false);
    txtInputParameter3.setText("");
    txtInputParameter3.setVisible(false);
    btnAdd.setVisible(false);
    btn3Sides.setVisible(true);
    btnBAndH.setVisible(true);
    lblTxtParameter1.setText("base:");
    lblTxtParameter1.setVisible(true);
    txtInputParameter1.setVisible(true);
    lblTxtParameter2.setText("altura:");
    lblTxtParameter2.setVisible(true);
    txtInputParameter2.setVisible(true);
  }//GEN-LAST:event_btnBAndHActionPerformed

  private void btn3SidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3SidesActionPerformed
    //esconde/mostra componentes referentes ao tipo do botao(3 lados)
    lblTxtParameter1.setText("Lado 1:");
    lblTxtParameter1.setVisible(true);
    txtInputParameter1.setVisible(true);
    lblTxtParameter2.setText("Lado 2:");
    lblTxtParameter2.setVisible(true);
    txtInputParameter2.setVisible(true);
    lblTxtParameter3.setText("Lado 3:");
    lblTxtParameter3.setVisible(true);
    txtInputParameter3.setVisible(true);
  }//GEN-LAST:event_btn3SidesActionPerformed

  private void txtInputParameter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputParameter1ActionPerformed
    verificarCampos();
  }//GEN-LAST:event_txtInputParameter1ActionPerformed

  private void txtInputParameter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputParameter2ActionPerformed
    verificarCampos();
  }//GEN-LAST:event_txtInputParameter2ActionPerformed

  private void txtInputParameter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputParameter3ActionPerformed
    verificarCampos();
  }//GEN-LAST:event_txtInputParameter3ActionPerformed

  private void txtInputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputNameActionPerformed
    verificarCampos();
  }//GEN-LAST:event_txtInputNameActionPerformed

  /**
   * @param args the command line arguments
   */
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton btn3Sides;
  private javax.swing.JToggleButton btnAdd;
  private javax.swing.JRadioButton btnBAndH;
  private javax.swing.JRadioButton btnBi;
  private javax.swing.ButtonGroup btnGpBiOrTri;
  private javax.swing.ButtonGroup btnGpDataType;
  private javax.swing.JRadioButton btnTri;
  private javax.swing.JComboBox<String> cbFormSelector;
  private javax.swing.JLabel lblTxtName;
  private javax.swing.JLabel lblTxtParameter1;
  private javax.swing.JLabel lblTxtParameter2;
  private javax.swing.JLabel lblTxtParameter3;
  private javax.swing.JLabel lblTxtSelectForm;
  private javax.swing.JTextField txtInputName;
  private javax.swing.JTextField txtInputParameter1;
  private javax.swing.JTextField txtInputParameter2;
  private javax.swing.JTextField txtInputParameter3;
  // End of variables declaration//GEN-END:variables
}
