/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade11.view;

import br.com.ifba.atividade11.forma.FormList;
import br.com.ifba.atividade11.forma.Forma;
import java.awt.Component;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;

/**
 *
 * @author gerviz
 */
public class MainFrame extends javax.swing.JFrame {

  private FormList formList;

  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    //cria uma lista de formas
    this.formList = new FormList();
    initComponents();
// muda o rendererer do combobox para mostrar somente o nome
    cbFormas.setRenderer(new DefaultListCellRenderer() {
      @Override
      public Component getListCellRendererComponent(JList<?> list, Object value,
          int index, boolean isSelected, boolean cellHasFocus) {
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (value instanceof Forma) {
          setText(((Forma) value).getNome());
        } else {
          setText("");
        }
        return this;
      }
    });

  }
// atualiza o combobox com os itens salvos em formas
  public void atualizarBx() {
    cbFormas.removeAllItems();
    for (Forma f : formList.getFormas()) {
      cbFormas.addItem(f);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cbFormas = new javax.swing.JComboBox<>();
    btnAddForm = new javax.swing.JToggleButton();
    lblTxtNameSelect = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txtParameters = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    cbFormas.setMaximumSize(new java.awt.Dimension(25, 32767));
    cbFormas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbFormasActionPerformed(evt);
      }
    });
    getContentPane().add(cbFormas, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 12, -1, -1));

    btnAddForm.setText("Adicionar forma");
    btnAddForm.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddFormActionPerformed(evt);
      }
    });
    getContentPane().add(btnAddForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 252, -1, -1));

    lblTxtNameSelect.setText("selecione o nome da forma:");
    getContentPane().add(lblTxtNameSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 16, -1, -1));

    txtParameters.setEditable(false);
    txtParameters.setColumns(20);
    txtParameters.setRows(5);
    jScrollPane1.setViewportView(txtParameters);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 49, -1, 229));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnAddFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFormActionPerformed
    atualizarBx();
    //chama a tela secundaria
    CreationFrame frame = new CreationFrame(this, formList);
    frame.setVisible(true);
  }//GEN-LAST:event_btnAddFormActionPerformed

  private void cbFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormasActionPerformed
    //busca a forma e os dados dela e escreve em um jTextArea
    Forma selecionada = (Forma) cbFormas.getSelectedItem();
    if (selecionada != null) {
      txtParameters.setText(selecionada.toString());
    } else {
      txtParameters.setText("");
    }
  }//GEN-LAST:event_cbFormasActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton btnAddForm;
  private javax.swing.JComboBox<Forma> cbFormas;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lblTxtNameSelect;
  private javax.swing.JTextArea txtParameters;
  // End of variables declaration//GEN-END:variables
}
