/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade07.view;

import javax.swing.JOptionPane;
import br.com.ifba.atividade07.controller.fatorialController;

/**
 *
 * @author gerviz
 */
public class MainFrame extends javax.swing.JFrame {

    private final fatorialController controller = new fatorialController();

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        btnCalcular.addActionListener(e -> {
            int valor = (int) spnNum.getValue();
            if (valor < 1) {
                JOptionPane.showMessageDialog(this, "valores como 0 ou numeros"
                        + " negativos não são aceitos");
            } else {
                lblResultado.setText("Resultado: "
                        + controller.getFatorial(valor));

                txtFormula.setText(controller.getFormula(valor)
                        + " = " + controller.getFatorial(valor));
            }
        });

        spnNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1)); // min 1, max 30

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorTxt = new javax.swing.JLabel();
        spnNum = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        JScrollPane = new javax.swing.JScrollPane();
        txtFormula = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValorTxt.setText("valor:");
        getContentPane().add(lblValorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));
        getContentPane().add(spnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 13, -1, -1));

        btnCalcular.setText("Calcular");
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 13, -1, -1));

        lblResultado.setText("Resultado: 0");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, -1, -1));

        txtFormula.setEditable(false);
        txtFormula.setColumns(20);
        txtFormula.setRows(5);
        JScrollPane.setViewportView(txtFormula);

        getContentPane().add(JScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 79, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblValorTxt;
    private javax.swing.JSpinner spnNum;
    private javax.swing.JTextArea txtFormula;
    // End of variables declaration//GEN-END:variables
}
