/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.atividade08.view;

import br.com.ifba.atividade08.accountController.account;
import br.com.ifba.atividade08.controller.BankController;
/**
 *
 * @author gerviz
 */
import java.util.Random;

public class criarConta extends javax.swing.JDialog {

  private final MainFrame mainRef;

  /**
   * Creates new form criarConta
   *
   * @param parent
   * @param modal
   * @param mainRef
   */
  public criarConta(java.awt.Frame parent, boolean modal, MainFrame mainRef) {
    super(parent, modal);
    initComponents();
    this.mainRef = mainRef;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    txtTitulo = new javax.swing.JLabel();
    btnCp = new javax.swing.JRadioButton();
    btnCc = new javax.swing.JRadioButton();
    bxName = new javax.swing.JComboBox<>();
    txtName = new javax.swing.JLabel();
    btnCriarContaFinal = new javax.swing.JToggleButton();

    setPreferredSize(new java.awt.Dimension(329, 167));
    setResizable(false);
    setSize(new java.awt.Dimension(512, 512));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtTitulo.setText("criando Conta");
    getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

    buttonGroup1.add(btnCp);
    btnCp.setSelected(true);
    btnCp.setText("conta poupança");
    btnCp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCpActionPerformed(evt);
      }
    });
    getContentPane().add(btnCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

    buttonGroup1.add(btnCc);
    btnCc.setText("conta corrente");
    getContentPane().add(btnCc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

    bxName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jubileu", "Creuza" }));
    getContentPane().add(bxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

    txtName.setText("nome:");
    getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

    btnCriarContaFinal.setText("Criar conta");
    btnCriarContaFinal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCriarContaFinalActionPerformed(evt);
      }
    });
    getContentPane().add(btnCriarContaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnCpActionPerformed

  private void btnCriarContaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarContaFinalActionPerformed
    // Cria uma instância do gerador de números aleatórios
    Random rand = new Random();

    // Gera um número aleatório de 7 dígitos (entre 1000000 e 9999999)
    int contaNum = rand.nextInt(9000000) + 1000000;

    // Pega o nome do combo box e o tipo de conta selecionado
    String nome = bxName.getSelectedItem().toString();
    String tipoConta = btnCp.isSelected() ? "Poupança" : "Corrente";

    // Cria uma nova conta
    account novaConta = new account(contaNum, tipoConta, nome, 0.0, false);

    // Chama o método openAccount
    novaConta.openAccount();
    bxName.removeItem(nome);
    mainRef.bxOwner.addItem(nome);
    BankController.adicionarConta(novaConta);
    //dispara evento de buscar dados da conta no mainframe
    mainRef.atualizarTela();
    dispose();
  }//GEN-LAST:event_btnCriarContaFinalActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(criarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(criarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(criarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(criarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        MainFrame mainFrame = new MainFrame();
        criarConta dialog = new criarConta(new javax.swing.JFrame(), true, mainFrame);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton btnCc;
  private javax.swing.JRadioButton btnCp;
  private javax.swing.JToggleButton btnCriarContaFinal;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JComboBox<String> bxName;
  private javax.swing.JLabel txtName;
  private javax.swing.JLabel txtTitulo;
  // End of variables declaration//GEN-END:variables
}
