/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

import javax.swing.SpinnerNumberModel;
import javax.swing.JSpinner;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author gerviz
 */
public class MainFrame extends javax.swing.JFrame {

  private ImageIcon genio;
  private ImageIcon Balao;

  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    initComponents();
    // Carrega a imagem original
    Balao = new ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/BalãoDeFala.png"));
    genio = new ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/gênio.jpg"));
    // Redimensiona ao iniciar
    ajustarImagens();

    // Atualiza a imagem sempre que o label for redimensionado
    lblGenio.addComponentListener(new ComponentAdapter() {
      @Override
      public void componentResized(ComponentEvent e) {
        ajustarImagens();
      }
    });

    lblBalaoDeFala.addComponentListener(new ComponentAdapter() {
      @Override
      public void componentResized(ComponentEvent e) {
        ajustarImagens();
      }
    });
  }
  //ajusta imagens

  private void ajustarImagens() {
    if (Balao != null && lblGenio.getWidth() > 0 && lblGenio.getHeight() > 0) {
      Image imagemRedimensionada = Balao.getImage().getScaledInstance(
          lblGenio.getWidth(), lblGenio.getHeight(), Image.SCALE_SMOOTH);
      lblGenio.setIcon(new ImageIcon(imagemRedimensionada));
    }
    if (genio != null && lblBalaoDeFala.getWidth() > 0 && lblBalaoDeFala.getHeight() > 0) {
      Image imagemRedimensionada;
      imagemRedimensionada = genio.getImage().getScaledInstance(
          lblBalaoDeFala.getWidth(), lblBalaoDeFala.getHeight(), Image.SCALE_SMOOTH);
      lblBalaoDeFala.setIcon(new ImageIcon(imagemRedimensionada));
    }
  }
  // gera um numerode 1 a 5

  public int GerarNumeroAleatorio() {
    return (int) (Math.random() * 5) + 1;
  }
  // checa se dois numeros são iguais

  public boolean ChecarSeDoisNumerosSaoIguais(int num1, int num2) {
    return num1 == num2;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainText = new javax.swing.JLabel();
        spnSelectPalpite = new JSpinner(new SpinnerNumberModel(1, 1, 5, 1));
        lblGenio = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        lblBalaoDeFala = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMainText.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        lblMainText.setText("<html>vou pensar em um número,tente adivinha-lo</html>");

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/BalãoDeFala.png"))); // NOI18N

        btnPalpite.setText("Palpite");

        lblBalaoDeFala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/gênio.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnSelectPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPalpite))
                .addGap(56, 56, 56)
                .addComponent(lblBalaoDeFala, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblMainText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblGenio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(spnSelectPalpite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnPalpite))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblBalaoDeFala, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblMainText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblGenio, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        //confere se o usuario acertou e adiciona o texto correspondente no label
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int palpite = (int) spnSelectPalpite.getValue();
                int numeroSorteado = GerarNumeroAleatorio();

                boolean acertou = ChecarSeDoisNumerosSaoIguais(palpite, numeroSorteado);

                if (acertou) {
                    lblMainText.setText("parabéns, você acertou!!!");
                } else {
                    lblMainText.setText("errou! o número era: " + numeroSorteado);
                }
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainFrame().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblBalaoDeFala;
    private javax.swing.JLabel lblGenio;
    public javax.swing.JLabel lblMainText;
    private javax.swing.JSpinner spnSelectPalpite;
    // End of variables declaration//GEN-END:variables
}
