/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09.view;

import br.com.ifba.atividade09.interfaces.paymentInterface;
import br.com.ifba.atividade09.paymentMethods.CardPayment;
import br.com.ifba.atividade09.paymentMethods.MoneyPayment;
import br.com.ifba.atividade09.paymentMethods.PixPayment;
import javax.swing.JOptionPane;

/**
 *
 * @author gerviz
 */
public class MainFrame extends javax.swing.JFrame {

  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnPay = new javax.swing.JToggleButton();
    txtInName = new javax.swing.JTextField();
    txtInValue = new javax.swing.JTextField();
    txtName = new javax.swing.JLabel();
    txtValue = new javax.swing.JLabel();
    lblTxtPayMet = new javax.swing.JLabel();
    bxInPayMet = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Pagamento");
    setPreferredSize(new java.awt.Dimension(348, 266));
    setResizable(false);
    setSize(new java.awt.Dimension(1024, 1024));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnPay.setText("Pagar");
    btnPay.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPayActionPerformed(evt);
      }
    });
    getContentPane().add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

    txtInName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    getContentPane().add(txtInName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 90, -1));

    txtInValue.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtInValueActionPerformed(evt);
      }
    });
    getContentPane().add(txtInValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 90, -1));

    txtName.setText("Nome:");
    getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

    txtValue.setText("valor:");
    getContentPane().add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

    lblTxtPayMet.setText("forma de pagamento");
    getContentPane().add(lblTxtPayMet, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

    bxInPayMet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a forma", "Pagamento Cartão", "Pagamento Dinheiro", "Pagamento Pix" }));
    bxInPayMet.setSelectedItem(null);
    getContentPane().add(bxInPayMet, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
    int PaymentType = (int) bxInPayMet.getSelectedIndex();
    String valueIn = txtInValue.getText().trim();
    String NameIn = txtInName.getText().trim();

    if (NameIn.isEmpty()) {
      JOptionPane.showMessageDialog(
          this,
          "O campo de nome está vazio.",
          "Erro",
          JOptionPane.ERROR_MESSAGE
      );
      return;
    }

    if (valueIn.isEmpty()) {
      JOptionPane.showMessageDialog(
          this,
          "O campo de valor está vazio.",
          "Erro",
          JOptionPane.ERROR_MESSAGE
      );
      return;
    }

    double valor;
    try {
      valor = Double.parseDouble(valueIn);
      if (valor <= 0) {
        JOptionPane.showMessageDialog(
            this,
            "O valor deve ser maior que zero.",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
        return;
      }
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(
          this,
          "Digite um número válido no campo de valor.",
          "Erro",
          JOptionPane.ERROR_MESSAGE
      );
      return;
    }

    paymentInterface pagamento = null;
    switch (PaymentType) {

      case 1:
        pagamento = new CardPayment();
        break;
      case 2:
        pagamento = new MoneyPayment();
        break;
      case 3:
        pagamento = new PixPayment();
        break;
      default:
        JOptionPane.showMessageDialog(
            this,
            "Selecione um método de pagamento!",
            "erro",
            JOptionPane.ERROR_MESSAGE
        );
        break;
    }
  }//GEN-LAST:event_btnPayActionPerformed

  private void txtInValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInValueActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtInValueActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainFrame().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton btnPay;
  private javax.swing.JComboBox<String> bxInPayMet;
  private javax.swing.JLabel lblTxtPayMet;
  private javax.swing.JTextField txtInName;
  private javax.swing.JTextField txtInValue;
  private javax.swing.JLabel txtName;
  private javax.swing.JLabel txtValue;
  // End of variables declaration//GEN-END:variables
}
