/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade18.view;

import br.com.ifba.atividade18.aluno.controller.AlunoController;
import br.com.ifba.atividade18.aluno.entity.AlunoA18;
import br.com.ifba.atividade18.curso.controller.CursoController;
import br.com.ifba.atividade18.curso.entity.CursoA18;
import br.com.ifba.atividade18.tableModel.TableAlunoModel;
import jakarta.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author gerviz
 */
@Component
public class AddOrEditAluno extends javax.swing.JDialog {

  @Autowired
  private AlunoController controller;

  @Autowired
  private CursoController controllerCurso;

  boolean editando = false;
  AlunoA18 alunoOriginal = new AlunoA18();
  public TableAlunoModel table;

  /**
   * Creates new form AddAluno
   */
  public AddOrEditAluno() {
    initComponents();
  }

  public AddOrEditAluno(AlunoListar parent, AlunoA18 aluno, TableAlunoModel table, AlunoController controller) {
    super(parent);
    this.table = table;
    this.controller = controller;
    this.controllerCurso = controllerCurso;

    initComponents();
    editando = false;
  }

  public void limparCampos() {
    txtInMatricula.setText("");
    txtInName.setText("");
    txtInCpf.setText("");
    cbxCursoIn.setSelectedIndex(0);
    chkInActive.setSelected(false);
    lblId.setText("");
  }

  @PostConstruct
  public void popularComboBox() {
    cbxCursoIn.removeAllItems();
    CursoA18 placeholderCurso = new CursoA18();
    placeholderCurso.setNome("Selecione o curso");
    List<CursoA18> cursos = new ArrayList<>();
    cursos.add(0, placeholderCurso);
    cursos.addAll(controllerCurso.findAll());
    for (CursoA18 curso : cursos) {
      cbxCursoIn.addItem(curso);
    }
  }

  public void popularComboBoxEdit(AlunoA18 aluno) {
    cbxCursoIn.removeAllItems();
    List<CursoA18> cursos = new ArrayList<>();
    CursoA18 cursoDoAluno = aluno.getCurso();
    cursos.add(0, cursoDoAluno);
    cursos.addAll(controllerCurso.findAll());
    for (CursoA18 curso : cursos) {
      cbxCursoIn.addItem(curso);
    }
  }

  public void iniciarEdicao(AlunoA18 aluno) {
    txtInName.setText(aluno.getNome());
    txtInMatricula.setText(aluno.getMatricula());
    txtInCpf.setText(aluno.getCpf());
    popularComboBoxEdit(aluno);
    chkInActive.setSelected(aluno.isAtivo());
    btnAdd.setText("Editar");
    lblId.setText("id: " + aluno.getId());
    editando = true;
    alunoOriginal = aluno;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblTxtName = new javax.swing.JLabel();
    txtInName = new javax.swing.JTextField();
    btnCancel = new javax.swing.JButton();
    btnAdd = new javax.swing.JButton();
    lblId = new javax.swing.JLabel();
    lblTxtMatricula = new javax.swing.JLabel();
    txtInMatricula = new javax.swing.JTextField();
    txtInCpf = new javax.swing.JTextField();
    lblTxtCpf = new javax.swing.JLabel();
    lblTxtCurso = new javax.swing.JLabel();
    lblTxtAtivo = new javax.swing.JLabel();
    chkInActive = new javax.swing.JCheckBox();
    cbxCursoIn = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Preencha os dados do aluno");
    setAutoRequestFocus(false);
    setIconImages(null);
    setName("AddCurso"); // NOI18N
    setResizable(false);
    setSize(new java.awt.Dimension(390, 250));
    setType(java.awt.Window.Type.UTILITY);

    lblTxtName.setText("nome:");

    btnCancel.setText("Cancelar");
    btnCancel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelActionPerformed(evt);
      }
    });

    btnAdd.setText("Adicionar");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });

    lblTxtMatricula.setText("matricula:");

    lblTxtCpf.setText("cpf:");

    lblTxtCurso.setText("curso:");

    lblTxtAtivo.setText("ativo:");

    cbxCursoIn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbxCursoInActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTxtMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addComponent(lblTxtCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lblTxtCurso)
                  .addComponent(lblTxtAtivo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(chkInActive))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxCursoIn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap(176, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lblTxtName)
            .addGap(35, 35, 35)
            .addComponent(txtInName)
            .addGap(19, 19, 19))))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnCancel)
        .addGap(18, 18, 18)
        .addComponent(btnAdd)
        .addGap(16, 16, 16))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTxtName)
          .addComponent(txtInName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTxtMatricula)
          .addComponent(txtInMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTxtCpf)
          .addComponent(txtInCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(lblTxtCurso))
          .addGroup(layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(cbxCursoIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(20, 20, 20)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblTxtAtivo)
          .addComponent(chkInActive))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnCancel)
          .addComponent(btnAdd))
        .addContainerGap(17, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    limparCampos();
    this.dispose();
  }//GEN-LAST:event_btnCancelActionPerformed

  private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    if (txtInName.getText().isBlank()
        || txtInMatricula.getText().isBlank()
        || txtInCpf.getText().isBlank()) {
      JOptionPane.showMessageDialog(
          null,
          "Preencha todos os campos! Há algo em branco.",
          "Erro",
          JOptionPane.ERROR_MESSAGE
      );
    } else {

      if (editando) {
        alunoOriginal.setAtivo(chkInActive.isSelected());
        alunoOriginal.setNome(txtInName.getText());
        alunoOriginal.setMatricula(txtInMatricula.getText());
        alunoOriginal.setCpf(txtInCpf.getText());
        alunoOriginal.setCurso((CursoA18) cbxCursoIn.getSelectedItem());
        controller.update(alunoOriginal);
        limparCampos();
        JOptionPane.showMessageDialog(this, "Aluno editado com sucesso!");
      } else if (cbxCursoIn.getSelectedIndex() != 0) {
        AlunoA18 aluno = new AlunoA18();
        aluno.setNome(txtInName.getText());
        aluno.setMatricula(txtInMatricula.getText());
        aluno.setCpf(txtInCpf.getText());
        aluno.setCurso((CursoA18) cbxCursoIn.getSelectedItem());
        aluno.setAtivo(chkInActive.isSelected());
        controller.save(aluno);
        limparCampos();
        JOptionPane.showMessageDialog(this, "Aluno adicionado com sucesso!");
      } else {
        JOptionPane.showMessageDialog(
            null,
            "Preencha todos os campos! Há algo em branco.",
            "Erro",
            JOptionPane.ERROR_MESSAGE
        );
      }
      if (table != null) {
        table.setDados(controller.findAll());
        table.fireTableDataChanged();
      }
      this.dispose();
    }
  }//GEN-LAST:event_btnAddActionPerformed

  private void cbxCursoInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursoInActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_cbxCursoInActionPerformed

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnCancel;
  private javax.swing.JComboBox<CursoA18> cbxCursoIn;
  private javax.swing.JCheckBox chkInActive;
  private javax.swing.JLabel lblId;
  private javax.swing.JLabel lblTxtAtivo;
  private javax.swing.JLabel lblTxtCpf;
  private javax.swing.JLabel lblTxtCurso;
  private javax.swing.JLabel lblTxtMatricula;
  private javax.swing.JLabel lblTxtName;
  private javax.swing.JTextField txtInCpf;
  private javax.swing.JTextField txtInMatricula;
  private javax.swing.JTextField txtInName;
  // End of variables declaration//GEN-END:variables
}
