/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade18.view;

import br.com.ifba.atividade18.aluno.repository.AlunoRepository;
import br.com.ifba.atividade18.curso.repository.CursoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author gerviz
 */
@Component
public class HomeForm extends javax.swing.JFrame {

  @Autowired
  public CursoRepository cursos;
  @Autowired
  public AlunoRepository alunos;
  @Autowired
  private ConfigurableApplicationContext context;

  /**
   * Creates new form HomeForm
   */

  public HomeForm() {
    initComponents();
    this.addWindowListener(new java.awt.event.WindowAdapter() {
      @Override
      public void windowOpened(java.awt.event.WindowEvent e) {
        AtualizarQuantidades();
      }
    });
  }

  public void AtualizarQuantidades() {
    lblQtdCursos.setText("Cursos: " + cursos.count());
    lblQtdAlunos.setText("Alunos: " + alunos.count());
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnClose = new javax.swing.JButton();
    btnListarCursos = new javax.swing.JButton();
    btnListarAlunos = new javax.swing.JButton();
    lblQtdCursos = new javax.swing.JLabel();
    lblQtdAlunos = new javax.swing.JLabel();
    lblBackground = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Gerenciar");
    setPreferredSize(new java.awt.Dimension(360, 270));
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnClose.setText("Sair");
    getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

    btnListarCursos.setText("Cursos");
    btnListarCursos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnListarCursosActionPerformed(evt);
      }
    });
    getContentPane().add(btnListarCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

    btnListarAlunos.setText("Alunos");
    btnListarAlunos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnListarAlunosActionPerformed(evt);
      }
    });
    getContentPane().add(btnListarAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

    lblQtdCursos.setForeground(new java.awt.Color(255, 255, 255));
    lblQtdCursos.setText("Cursos: ...");
    getContentPane().add(lblQtdCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

    lblQtdAlunos.setForeground(new java.awt.Color(255, 255, 255));
    lblQtdAlunos.setText("Alunos: ...");
    getContentPane().add(lblQtdAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

    lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade12/view/images/backgroung.png"))); // NOI18N
    lblBackground.setMaximumSize(new java.awt.Dimension(400, 300));
    lblBackground.setMinimumSize(new java.awt.Dimension(400, 300));
    lblBackground.setPreferredSize(new java.awt.Dimension(400, 300));
    getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 390, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCursosActionPerformed
    CursoListar dialog = context.getBean(CursoListar.class);
    dialog.setLocationRelativeTo(this);
    this.setVisible(false);
    dialog.setVisible(true);
  }//GEN-LAST:event_btnListarCursosActionPerformed

  private void btnListarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarAlunosActionPerformed
    AlunoListar dialog = context.getBean(AlunoListar.class);
    dialog.setLocationRelativeTo(this);
    this.setVisible(false);
    dialog.setVisible(true);
  }//GEN-LAST:event_btnListarAlunosActionPerformed

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnClose;
  private javax.swing.JButton btnListarAlunos;
  private javax.swing.JButton btnListarCursos;
  private javax.swing.JLabel lblBackground;
  private javax.swing.JLabel lblQtdAlunos;
  private javax.swing.JLabel lblQtdCursos;
  // End of variables declaration//GEN-END:variables
}
