/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade06.view;

import javax.swing.JOptionPane;
import br.com.ifba.atividade06.controller.ListController;
import java.util.List;

/**
 *
 * @author gerviz
 */
public class MainFrame extends javax.swing.JFrame {

  private final ListController controller = new ListController();

  /**
   * Creates new form MainFrame
   */
  public MainFrame() {
    initComponents();
//checa se tem algum item selecionado na lista e adiciona um elemento no local
    btnAdd.addActionListener(e -> {
      int index = lstItens.getSelectedIndex();
      if (index >= 0 && index < 10) {
        int novoValor = (int) spnNum.getValue();
        controller.atualizar(index, novoValor);
        atualizarLista();
      } else {
        JOptionPane.showMessageDialog(this, "Selecione um item primeiro.");
      }
    });
//checa se tem algum item selecionado na lista e remove um elemento no local
    btnRemove.addActionListener(e -> {
      int index = lstItens.getSelectedIndex();
      if (index >= 0) {
        controller.atualizar(index, 0);
        atualizarLista();
      } else {
        JOptionPane.showMessageDialog(this, "Selecione um item primeiro.");
      }

    });
//ordena a lista
    btnOrdena.addActionListener(e -> {
      controller.ordenar();
      atualizarLista();
    });

  }
//atualiza a lista na tela

  private void atualizarLista() {
    List<Integer> dados = controller.getLista();
    String[] itens = new String[dados.size()];
    for (int i = 0; i < dados.size(); i++) {
      itens[i] = "[" + i + "] -> " + dados.get(i);
    }
    lstItens.setListData(itens);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnNum = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnOrdena = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstItens = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(spnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 90, -1));

        btnAdd.setText("Adicionar");
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, -1));

        btnRemove.setText("Remover");
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, -1));

        btnOrdena.setText("Ordenar");
        getContentPane().add(btnOrdena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, -1));

        lstItens.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "[0] -> 0", "[1] -> 0", "[2] -> 0", "[3] -> 0", "[4] -> 0", "[5] -> 0", "[6] -> 0", "[7] -> 0", "[8] -> 0", "[9] -> 0" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstItens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstItens);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 90, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainFrame().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnOrdena;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstItens;
    private javax.swing.JSpinner spnNum;
    // End of variables declaration//GEN-END:variables
}
